from ofcsst.figures.supplementary import fs1d_paopt
from ofcsst.figures.supplementary import fs2_texture_response
from ofcsst.figures.supplementary import fs3_snr
from ofcsst.figures.supplementary import fs4bc
from ofcsst.figures.supplementary import fs4def
from ofcsst.figures.supplementary import fs5_reset
from ofcsst.figures.supplementary import fs6_optimization
from ofcsst.figures.supplementary import fs7_multi_rev_no_gain
from ofcsst.figures.supplementary import fs8_multi_rev_ofc
