from ofcsst.figures.main import f1e_explore_distractor
from ofcsst.figures.main import f1f_explore_gain
from ofcsst.figures.main import f1h_gain_vs_no_gain
from ofcsst.figures.main import f1i_relative_gain
from ofcsst.figures.main import f2b_predicted_variance
from ofcsst.figures.main import f2cef_reversal
from ofcsst.figures.main import f3b_s1_xp
from ofcsst.figures.main import f3efg_ofc_sst
from ofcsst.figures.main import f4bcd_double_reversal
from ofcsst.figures.main import f4g_multicontext
from ofcsst.figures.main import f5a_VIP_CL
